### ISSUE TITLE
where's the best place to get help and give feedback?

### ISSUE THREAD

**Issue by benblo** [Unity-Technologies/ScriptableRenderLoop#374]
The [single forum thread](https://forum.unity3d.com/threads/feedback-wanted-scriptable-render-pipelines.470095/) kinda feels like a kitchen sink, the beta list is now defunct... is here the best place to talk to devs?

Is there any form of high-level documentation, release notes in-between tagged releases, anything?

I spent a few days exploring SRP about a month ago with 2017.1, and coming back to try 2017.2 I see a bunch of new parameters but no clue what they do, eg [cullingFlags](https://docs.unity3d.com/2017.2/Documentation/ScriptReference/Experimental.Rendering.ScriptableCullingParameters-cullingFlags.html), [sceneMask](https://docs.unity3d.com/2017.2/Documentation/ScriptReference/Experimental.Rendering.ScriptableCullingParameters-sceneMask.html)... though I understand this is all experimental, the docs are still sparse :) !
Also, what's the difference between [cullingMask](https://docs.unity3d.com/2017.2/Documentation/ScriptReference/Experimental.Rendering.ScriptableCullingParameters-cullingMask.html) and [layerCull](https://docs.unity3d.com/2017.2/Documentation/ScriptReference/Experimental.Rendering.ScriptableCullingParameters-layerCull.html)?

**Comment by nicobella** [comment]
I agree, it would be really useful both for users and for the developers involved in this stage, to have documentation at least a rough one but centralized, and a place to take suggestions and bug reports, I really want to start experiment with this feature with the less amount of headache trying to understand and guess how it works in the process, thanks!

**Comment by sebastienlagarde** [comment]
Hi, 
I agree that the communication around SRP have begin way too early and should have stay internal.
There is no documentation yet because the feature SRP is very experimental and is not suppose to be use in any productions for this year.

Some clarification about SRP and what you can find in the github repository.
- SRP (scriptable render pipeline) is the features that allow you to build your own pipeline
- BasicRenderPipeline is a very basic example of a pipeline build on SRP feature that rely on vanilla Unity shaders
- LT (LightWeight pipeline) is an example of a pipeline build on SRP feature that target non-compute-capable platform (mainly low end mobile) and reuse some code/concept of vanilla Unity shader but include a lot of new shader code
- HD (High definition pipeline) is an example of a pipeline build on SRP feature that target compute-capable platform (mainly PC/Console) and use a totally new set of shaders not compatible with vanilla Unity (It mean that asset store plugin that rely on shaders code doesn't work with HD)
- FPTL is just a sandbox and will be remove in the future

When discussing about the feature SRP, it is important to distinguish the target topic: SRP, SRP/LT, SRP/HD so our team can forward the information to the right people.

SRP API still evolve and no documentation is available yet. Change in SRP API usually break C++ compatibility and require a new version of Unity. Thus why we create github release and why the latest github is not compatible with latest publicly available version.
LT is starting to stabilize and maybe release in beta in few month with documentation (just not started yet). It is a good start to build your own render pipeline.
HD is very experimental and is a way more complex pipeline. It is not stabilize and change frequently.

We are very aware of many culprits and trouble in current SRP API, a big one being the UI that require a lot of attention before we release anything. This is in progress to be fix and we may release a "working' experimental release in next few months. In this case, there will be an official announcement.
